"""
THIS FILE IS AUTOMATICALLY GENERATED BY A STATIC CODE GENERATION TOOL
DO NOT EDIT BY HAND

Instead edit the generator and run it:

    python tools/generate_units.py

Short unit names, which in most circumstances do not clash with local names:

    mV, uV, nV, pV, mA, uA, nA, pA, mF, uF, nF, pF, mS, uS, nS, pS, ms, us, ns,
    ps, Hz, kHz, MHz, GHz, cm, cm2, cm3, mm, mm2, mm3, um, um2, um3, mM, uM, nM,
    pM

Each is <prefix><symbol>; there are no single-letter names (no bare V, A, s, m).
"""

# isort:skip_file
# fmt: off
from .allunits import (
    mvolt,
    uvolt,
    nvolt,
    pvolt,
    mamp,
    uamp,
    namp,
    pamp,
    mfarad,
    ufarad,
    nfarad,
    pfarad,
    msiemens,
    usiemens,
    nsiemens,
    psiemens,
    msecond,
    usecond,
    nsecond,
    psecond,
    hertz,
    khertz,
    Mhertz,
    Ghertz,
    cmetre,
    cmetre2,
    cmetre3,
    mmetre,
    mmetre2,
    mmetre3,
    umetre,
    umetre2,
    umetre3,
    mmolar,
    umolar,
    nmolar,
    pmolar,
)
from .allunits import all_units

__all__ = [
    "mV",
    "uV",
    "nV",
    "pV",
    "mA",
    "uA",
    "nA",
    "pA",
    "mF",
    "uF",
    "nF",
    "pF",
    "mS",
    "uS",
    "nS",
    "pS",
    "ms",
    "us",
    "ns",
    "ps",
    "Hz",
    "kHz",
    "MHz",
    "GHz",
    "cm",
    "cm2",
    "cm3",
    "mm",
    "mm2",
    "mm3",
    "um",
    "um2",
    "um3",
    "mM",
    "uM",
    "nM",
    "pM",
]

mV = mvolt
uV = uvolt
nV = nvolt
pV = pvolt
mA = mamp
uA = uamp
nA = namp
pA = pamp
mF = mfarad
uF = ufarad
nF = nfarad
pF = pfarad
mS = msiemens
uS = usiemens
nS = nsiemens
pS = psiemens
ms = msecond
us = usecond
ns = nsecond
ps = psecond
Hz = hertz
kHz = khertz
MHz = Mhertz
GHz = Ghertz
cm = cmetre
cm2 = cmetre2
cm3 = cmetre3
mm = mmetre
mm2 = mmetre2
mm3 = mmetre3
um = umetre
um2 = umetre2
um3 = umetre3
mM = mmolar
uM = umolar
nM = nmolar
pM = pmolar

stdunits = {
    "mV": mV,
    "uV": uV,
    "nV": nV,
    "pV": pV,
    "mA": mA,
    "uA": uA,
    "nA": nA,
    "pA": pA,
    "mF": mF,
    "uF": uF,
    "nF": nF,
    "pF": pF,
    "mS": mS,
    "uS": uS,
    "nS": nS,
    "pS": pS,
    "ms": ms,
    "us": us,
    "ns": ns,
    "ps": ps,
    "Hz": Hz,
    "kHz": kHz,
    "MHz": MHz,
    "GHz": GHz,
    "cm": cm,
    "cm2": cm2,
    "cm3": cm3,
    "mm": mm,
    "mm2": mm2,
    "mm3": mm3,
    "um": um,
    "um2": um2,
    "um3": um3,
    "mM": mM,
    "uM": uM,
    "nM": nM,
    "pM": pM,
}
all_units.extend(stdunits.values())
# fmt: on
