"""Generate ``src/QuantSI/allunits.py``, the catalogue of named units.

The generated file is committed (an editor or type checker sees every unit as
an ordinary module-level name), and CI checks that it matches what this script
generates. After changing this script, regenerate it::

    python tools/generate_units.py

and commit both files together. Moved here from Brian2's
``dev/tools/static_codegen`` (template and generator in one file).
"""

import pathlib

OUTPUT = pathlib.Path(__file__).parent.parent / "src" / "QuantSI" / "allunits.py"

#: The SI prefixes, in the order in which units are generated. The order looks
#: random because it is: it was the iteration order of a dict when the units were
#: first generated (Python 2). Keep it: when choosing a unit for display, the
#: registries break ties by registration order, so a different order would change
#: how some quantities are displayed.
SI_PREFIXES = ["a", "", "c", "Z", "P", "d", "G", "f", "h", "da", "m", "n", "p", "u"]
SI_PREFIXES += ["T", "y", "E", "z", "M", "k", "Y"]

FUNDAMENTAL_UNITS = ["metre", "meter", "kilogram", "second", "amp", "ampere", "kelvin"]
FUNDAMENTAL_UNITS += ["mole", "mol", "candle"]

#: Derived units, from http://physics.nist.gov/cuu/Units/units.html
DERIVED_UNITS = [
    ["radian", "rad", "get_or_create_dimension()"],
    ["steradian", "sr", "get_or_create_dimension()"],
    ["hertz", "Hz", "get_or_create_dimension(s= -1)"],
    ["newton", "N", "get_or_create_dimension(m=1, kg=1, s=-2)"],
    ["pascal", "Pa", "get_or_create_dimension(m= -1, kg=1, s=-2)"],
    ["joule", "J", "get_or_create_dimension(m=2, kg=1, s=-2)"],
    ["watt", "W", "get_or_create_dimension(m=2, kg=1, s=-3)"],
    ["coulomb", "C", "get_or_create_dimension(s=1, A=1)"],
    ["volt", "V", "get_or_create_dimension(m=2, kg=1, s=-3, A=-1)"],
    ["farad", "F", "get_or_create_dimension(m= -2, kg=-1, s=4, A=2)"],
    ["ohm", "ohm", "get_or_create_dimension(m=2, kg=1, s= -3, A=-2)"],
    ["siemens", "S", "get_or_create_dimension(m= -2, kg=-1, s=3, A=2)"],
    ["weber", "Wb", "get_or_create_dimension(m=2, kg=1, s=-2, A=-1)"],
    ["tesla", "T", "get_or_create_dimension(kg=1, s=-2, A=-1)"],
    ["henry", "H", "get_or_create_dimension(m=2, kg=1, s=-2, A=-2)"],
    ["lumen", "lm", "get_or_create_dimension(cd=1)"],
    ["lux", "lx", "get_or_create_dimension(m=-2, cd=1)"],
    ["becquerel", "Bq", "get_or_create_dimension(s=-1)"],
    ["gray", "Gy", "get_or_create_dimension(m=2, s=-2)"],
    ["sievert", "Sv", "get_or_create_dimension(m=2, s=-2)"],
    ["katal", "kat", "get_or_create_dimension(s=-1, mol=1)"],
]

HEADER = '''"""
THIS FILE IS AUTOMATICALLY GENERATED BY A STATIC CODE GENERATION TOOL
DO NOT EDIT BY HAND

Instead edit the generator and run it:

    python tools/generate_units.py
"""

# fmt: off
# flake8: noqa
import itertools

from .fundamentalunits import (
    Unit,
    additional_unit_register,
    get_or_create_dimension,
    standard_unit_register,
)
'''

FUNDAMENTAL_DEFINITIONS = """
Unit.automatically_register_units = False

#### FUNDAMENTAL UNITS
metre = Unit.create(get_or_create_dimension(m=1), "metre", "m")
meter = Unit.create(get_or_create_dimension(m=1), "meter", "m")
# Liter has a scale of 10^-3, since 1 l = 1 dm^3 = 10^-3 m^3
liter = Unit.create(dim=(meter**3).dim, name="liter", dispname="l", scale=-3)
litre = Unit.create(dim=(meter**3).dim, name="litre", dispname="l", scale=-3)
kilogram = Unit.create(get_or_create_dimension(kg=1), "kilogram", "kg")
kilogramme = Unit.create(get_or_create_dimension(kg=1), "kilogramme", "kg")
gram = Unit.create(dim=kilogram.dim, name="gram", dispname="g", scale=-3)
gramme = Unit.create(dim=kilogram.dim, name="gramme", dispname="g", scale=-3)
second = Unit.create(get_or_create_dimension(s=1), "second", "s")
amp = Unit.create(get_or_create_dimension(A=1), "amp", "A")
ampere = Unit.create(get_or_create_dimension(A=1), "ampere", "A")
kelvin = Unit.create(get_or_create_dimension(K=1), "kelvin", "K")
mole = Unit.create(get_or_create_dimension(mol=1), "mole", "mol")
mol = Unit.create(get_or_create_dimension(mol=1), "mol", "mol")
# Molar has a scale of 10^3, since 1 M = 1 mol/l = 1000 mol/m^3
molar = Unit.create((mole/liter).dim, name="molar", dispname="M", scale=3)
candle = Unit.create(get_or_create_dimension(candle=1), "candle", "cd")
fundamental_units = [metre, meter, gram, second, amp, kelvin, mole, candle]
"""

FOOTER = """
Unit.automatically_register_units = True

for unit in itertools.chain(powered_units, scaled_units, base_units):
    standard_unit_register.add(unit)
for unit in additional_units:
    additional_unit_register.add(unit)
# fmt: on
"""


def list_definition(name, items):
    return f"\n{name} = [\n" + "".join(f"    {item},\n" for item in items) + "    ]\n"


def generate():
    base_units = FUNDAMENTAL_UNITS + ["kilogramme", "gram", "gramme", "molar"]
    derived = ""
    for long_name, short_name, definition in DERIVED_UNITS:
        derived += f'{long_name} = Unit.create({definition}, "{long_name}", "{short_name}")\n'
        base_units.append(long_name)
    all_units = list(base_units)

    # Scaled versions of all base units (no "mkelvin", "kkilogram", ...)
    definitions = "######### SCALED BASE UNITS ###########\n"
    scaled_units = []
    excluded_scaled_units = set()  # deci, centi, deka and hecto are not used for display
    for base in base_units:
        if base in ["kelvin", "kilogram", "kilogramme"]:
            continue
        for prefix in SI_PREFIXES:
            if prefix:
                unit = prefix + base
                all_units.append(unit)
                definitions += f'{unit} = Unit.create_scaled_unit({base}, "{prefix}")\n'
                if prefix not in ["da", "d", "c", "h"]:
                    scaled_units.append(unit)
                else:
                    excluded_scaled_units.add(unit)

    # Second and third powers of all (scaled) base units
    definitions += "######### SCALED BASE UNITS TO POWERS ###########\n"
    powered_units = []
    for base in list(all_units):
        for power in [2, 3]:
            unit = f"{base}{power}"
            definitions += (
                f'{unit} = Unit.create(({base}**{power}).dim, name="{unit}", '
                f'dispname=f"{{str({base})}}^{power}", scale={base}.scale*{power})\n'
            )
            all_units.append(unit)
            if base not in excluded_scaled_units:
                powered_units.append(unit)

    additional_units = """
# Current list from http://physics.nist.gov/cuu/Units/units.html, far from complete
additional_units = [
    pascal * second, newton * metre, watt / metre ** 2, joule / kelvin,
    joule / (kilogram * kelvin), joule / kilogram, watt / (metre * kelvin),
    joule / metre ** 3, volt / metre ** 3, coulomb / metre ** 3, coulomb / metre ** 2,
    farad / metre, henry / metre, joule / mole, joule / (mole * kelvin),
    coulomb / kilogram, gray / second, katal / metre ** 3,
    # We don't want liter/litre to be used as a standard unit for display, so we
    # put it here instead of in the standard units
    """
    # Scaled liters, only for display as additional units (not liter**2, and never
    # chosen instead of metre**3 for volumes)
    for base in ["liter", "litre"]:
        all_units.append(base)
        for prefix in SI_PREFIXES:
            unit = prefix + base
            all_units.append(unit)
            definitions += f'{unit} = Unit.create_scaled_unit({base}, "{prefix}")\n'
            additional_units += unit + ", "
    additional_units += "]"

    names = "\n__all__ = [\n" + "".join(f'    "{unit}",\n' for unit in all_units) + "    ]\n"
    # For display, the registries prefer the unit defined last for a given scale,
    # so the lists are reversed to give the standard units precedence.
    return (
        HEADER
        + names
        + "\n"
        + FUNDAMENTAL_DEFINITIONS
        + "\n"
        + derived
        + "\n"
        + definitions
        + "\n\n"
        + list_definition("base_units", base_units[::-1])
        + "\n"
        + list_definition("scaled_units", scaled_units[::-1])
        + "\n"
        + list_definition("powered_units", powered_units[::-1])
        + "\n"
        + additional_units
        + "\n"
        + list_definition("all_units", all_units[::-1])
        + "\n"
        + FOOTER
    )


if __name__ == "__main__":
    OUTPUT.write_text(generate())
    print(f"wrote {OUTPUT}")
